### ISSUE TITLE
Sync fails if model_id is set to null in config

### ISSUE THREAD

**Issue by jgdwyer** [singer-io/tap-impact#12]
The tap will fail during the sync step if the model_id is set to null in config. 

Steps to reproduce:
- Set  `"model_id": null` in `config.json`
- Discover catalog with `tap-impact --config config.json --discover > catalog.json`
- Run the tap in sync mode `tap-impact --config config.json --catalog catalog.json > state.json`

Expected behavior:
- Sync completes successfully

Actual behavior:
- Raises TypeError when syncing a child stream of campaigns.
```
  File "/Users/jgdwyer/Desktop/tap-impact/tap_impact/sync.py", line 315, in sync_endpoint
    '<model_id>', model_id)
TypeError: replace() argument 2 must be str, not None
```

This happened to me while using the Tap with Singer. Initially I had not entered any value for model_id and the tap ran fine. Later I changed the integration frequency (but did not change the model_id) and the tap was failing. As best as I can tell, Singer is passing `model_id: null` in the config on updates to the settings (rather than an empty string or just omitting the field). As a temporarily workaround in Stitch I just entered a bogus numeric value for the model_id.

**Comment by kethan1122** [comment]
Closing this issue as it was fixed in PR #23
